// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as RefetchArticlePreviewProcedure from "../refetch_article_preview_procedure";

export type RefetchArticlePreviewArgs = __Infer<
  typeof RefetchArticlePreviewProcedure.params
>;
export type RefetchArticlePreviewResult = __Infer<
  typeof RefetchArticlePreviewProcedure.returnType
>;
