// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import RemarkArgumentsReducer from "../remark_arguments_reducer";
import UpdateSchedulersReducer from "../update_schedulers_reducer";

export type RemarkArgumentsParams = __Infer<typeof RemarkArgumentsReducer>;
export type UpdateSchedulersParams = __Infer<typeof UpdateSchedulersReducer>;
