// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import { Thumbnail } from "./types";

export default __t.row({
  pageId: __t.u64().primaryKey().name("page_id"),
  title: __t.string(),
  description: __t.option(__t.string()),
  summary: __t.string(),
  get thumbnail() {
    return __t.option(Thumbnail);
  },
  fetchedAt: __t.timestamp().name("fetched_at"),
  lastEditedAt: __t.timestamp().name("last_edited_at"),
});
