// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  rcId: __t.u64().primaryKey().name("rc_id"),
  pageId: __t.u64().name("page_id"),
  revId: __t.u64().name("rev_id"),
  oldRevId: __t.u64().name("old_rev_id"),
  title: __t.string(),
  userName: __t.string().name("user_name"),
  isBot: __t.bool().name("is_bot"),
  isMinor: __t.bool().name("is_minor"),
  isNew: __t.bool().name("is_new"),
  isTemp: __t.bool().name("is_temp"),
  isRedirect: __t.bool().name("is_redirect"),
  oldLen: __t.u32().name("old_len"),
  newLen: __t.u32().name("new_len"),
  comment: __t.string(),
  tags: __t.array(__t.string()),
  editedAt: __t.timestamp().name("edited_at"),
  live: __t.bool(),
  isRevert: __t.bool().name("is_revert"),
});
