// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Admin = __t.object("Admin", {
  identity: __t.identity(),
});
export type Admin = __Infer<typeof Admin>;

export const ArticlePreview = __t.object("ArticlePreview", {
  pageId: __t.u64(),
  title: __t.string(),
  description: __t.option(__t.string()),
  summary: __t.string(),
  get thumbnail() {
    return __t.option(Thumbnail);
  },
  fetchedAt: __t.timestamp(),
});
export type ArticlePreview = __Infer<typeof ArticlePreview>;

export const Edit = __t.object("Edit", {
  rcId: __t.u64(),
  pageId: __t.u64(),
  revId: __t.u64(),
  oldRevId: __t.u64(),
  title: __t.string(),
  userName: __t.string(),
  isBot: __t.bool(),
  isMinor: __t.bool(),
  isNew: __t.bool(),
  isTemp: __t.bool(),
  isRedirect: __t.bool(),
  oldLen: __t.u32(),
  newLen: __t.u32(),
  comment: __t.string(),
  tags: __t.array(__t.string()),
  editedAt: __t.timestamp(),
  live: __t.bool(),
});
export type Edit = __Infer<typeof Edit>;

// The tagged union or sum type for the algebraic type `FetchActivity`.
export const FetchActivity = __t.enum("FetchActivity", {
  get FetchingEdits() {
    return FetchingEdits;
  },
  get FetchedEdits() {
    return FetchedEdits;
  },
  EditsFailed: __t.string(),
  get FetchingPreviews() {
    return FetchingPreviews;
  },
  get FetchedPreviews() {
    return FetchedPreviews;
  },
  PreviewsFailed: __t.string(),
});
export type FetchActivity = __Infer<typeof FetchActivity>;

export const FetchLog = __t.object("FetchLog", {
  fetchId: __t.uuid(),
  get activity() {
    return FetchActivity;
  },
});
export type FetchLog = __Infer<typeof FetchLog>;

export const FetchedEdits = __t.object("FetchedEdits", {
  received: __t.u32(),
  added: __t.u32(),
});
export type FetchedEdits = __Infer<typeof FetchedEdits>;

export const FetchedPreviews = __t.object("FetchedPreviews", {
  stored: __t.u32(),
  missing: __t.u32(),
});
export type FetchedPreviews = __Infer<typeof FetchedPreviews>;

export const FetchingEdits = __t.object("FetchingEdits", {
  since: __t.timestamp(),
});
export type FetchingEdits = __Infer<typeof FetchingEdits>;

export const FetchingPreviews = __t.object("FetchingPreviews", {
  get pages() {
    return __t.array(PreviewPage);
  },
});
export type FetchingPreviews = __Infer<typeof FetchingPreviews>;

export const PollTimer = __t.object("PollTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type PollTimer = __Infer<typeof PollTimer>;

export const PollerStatus = __t.object("PollerStatus", {
  id: __t.u8(),
  cursor: __t.timestamp(),
  lastSuccessAt: __t.option(__t.timestamp()),
  lastError: __t.option(__t.string()),
  lastErrorAt: __t.option(__t.timestamp()),
  consecutiveFailures: __t.u32(),
  editsIngested: __t.u64(),
});
export type PollerStatus = __Infer<typeof PollerStatus>;

export const PreviewPage = __t.object("PreviewPage", {
  pageId: __t.u64(),
  title: __t.string(),
});
export type PreviewPage = __Infer<typeof PreviewPage>;

export const PreviewQueue = __t.object("PreviewQueue", {
  pageId: __t.u64(),
  title: __t.string(),
  attempts: __t.u8(),
  enqueuedAt: __t.timestamp(),
});
export type PreviewQueue = __Infer<typeof PreviewQueue>;

export const PruneTimer = __t.object("PruneTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type PruneTimer = __Infer<typeof PruneTimer>;

export const Settings = __t.object("Settings", {
  id: __t.u8(),
  wikipediaContact: __t.string(),
});
export type Settings = __Infer<typeof Settings>;

export const SweepTimer = __t.object("SweepTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type SweepTimer = __Infer<typeof SweepTimer>;

export const Thumbnail = __t.object("Thumbnail", {
  url: __t.string(),
  width: __t.u32(),
  height: __t.u32(),
});
export type Thumbnail = __Infer<typeof Thumbnail>;
